"""
Search links for Direct-to-Site Search feature.

Ported from reputeai_orchestrator Dedupe_Orchestrator/direct_to_site_searches/search_links.py
"""

DATABRICKS_TIER_1_BUSINESS = {
    "ABC News": "https://abcnews.go.com/search?searchtext=Databricks",
    "Associated Press": "https://apnews.com/search?q=Databricks#nt=navsearch",
    "Axios": "https://www.axios.com/results?q=Databricks&sort=1",
    "BBC": "https://www.bbc.com/search?q=Databricks",
    "Bloomberg": "https://www.bloomberg.com/search?query=Databricks",
    "Boston Business Journal": "https://www.bizjournals.com/boston/search?s=2&q=Databricks",
    "Boston Globe": "https://www.bostonglobe.com/search/?q=Databricks",
    "Business Insider": "https://www.businessinsider.com/answers#Databricks",
    "CBS News": "https://www.cbsnews.com/search/?q=Databricks",
    "CNBC": "https://www.cnbc.com/search/?query=Databricks&qsearchterm=Databricks",
    "CNN": "https://www.cnn.com/search?q=Databricks&from=0&size=10&page=1&sort=newest&types=all&section=",
    "Fast Company": "https://www.fastcompany.com/",
    "Financial Times": "https://www.ft.com/search?q=Databricks&sort=date&isFirstView=true",
    "Forbes": "https://www.forbes.com/search/?q=Databricks",
    "Fortune": "https://fortune.com/search/Databricks/",
    "Harvard Business Review": "https://hbr.org/search?term=Databricks",
    "Inc.": "https://www.inc.com/",
    "MIT Technology Review": "https://www.technologyreview.com/search/?s=Databricks",
    "Morning Brew": "https://www.morningbrew.com/search?tag=&q=Databricks",
    "NBC News": "https://www.nbcnews.com/search/?q=Databricks",
    "New York Times": "https://www.nytimes.com/search?dropmab=false&query=Databricks&sort=best",
    "Newsweek": "https://search.newsweek.com/",
    "NPR": "https://www.npr.org/search/?query=Databricks&page=1&range%5BlastModifiedDate%5D%5Bmin%5D=1752537600",
    "Politico": "https://www.politico.com/search?s=newest&userInitiated=true&q=Databricks",
    "Reuters": "https://www.reuters.com/site-search/?query=Databricks&date=past_week",
    "The Hill": "https://thehill.com/?s=Databricks&order=desc&orderby=relevance",
    "USA Today": "https://www.usatoday.com/search/?q=Databricks",
    "Wall Street Journal": "https://www.wsj.com/search?query=Databricks",
    "Washington Post": "https://www.washingtonpost.com/search/?query=Databricks+last+two+weeks",
    "WIRED": "https://www.wired.com/search/?q=Databricks&sort=publishdate+desc",
    "Yahoo! News": "https://news.search.yahoo.com/search?p=Databricks",
}

DATABRICKS_TIER_1_TRADE = {
    "Ars Technica": "https://arstechnica.com/#gsc.tab=0&gsc.q=Databricks&gsc.sort=date",
    "Bleeping Computer": "https://www.bleepingcomputer.com/search/Databricks/",
    "CIO.com": "https://www.cio.com/search/?q=Databricks",
    "CIO Dive": "https://www.ciodive.com/search/?q=Databricks&selected_facets=&topics=&sortby=on",
    "CNET": "https://www.cnet.com/search/?searchQuery=Databricks",
    "ComputerWeekly": "https://www.computerweekly.com/search",
    "Computerworld": "https://www.computerworld.com/search/?q=Databricks",
    "CPO Magazine": "https://www.cpomagazine.com/?s=Databricks",
    "CRN": "https://www.crn.com/search?q=Databricks",
    "CSO Online": "https://www.csoonline.com/search/?q=Databricks",
    "Cyberscoop": "https://cyberscoop.com/?s=databricks",
    "Cybersecurity Dive": "https://www.cybersecuritydive.com/search/?q=Databricks&selected_facets=section_exact%3Anews&topics=&sortby=on",
    "Dark Reading": "https://www.darkreading.com/search?q=Databricks&sort=newest",
    "Datamation": "https://www.datamation.com/?s=Databricks",
    "Decipher": "https://duo.com/search#?cludoquery=Databricks&cludopage=1&cludoinputtype=standard",
    "Dice Insights": "https://www.dice.com/career-advice/search?query=Databricks",
    "eSecurity Planet": "https://www.esecurityplanet.com/?s=Databricks",
    "eWEEK": "https://www.eweek.com/?s=Databricks",
    "InformationWeek": "https://www.informationweek.com/search?q=Databricks&sort=newest",
    "Infosecurity Magazine": "https://www.infosecurity-magazine.com/search/?keywords=Databricks",
    "InfoWorld": "https://www.infoworld.com/search/?q=Databricks",
    "ISMG": "https://www.ismg.io/search/Databricks",
    "IT Brew": "https://www.itbrew.com/search?q=databricks&search=nav",
    "ITPro Today": "https://www.itprotoday.com/search?q=Databricks&sort=newest",
    "Krebs on Security": "https://krebsonsecurity.com/?s=Databricks",
    "Runtime.News": "https://www.runtime.news/tag/databricks/",
    "SC Media": "https://www.scworld.com/search?q=Databricks",
    "SD Times": "https://sdtimes.com/?s=Databricks",
    "SDxCentral": "https://www.sdxcentral.com/sdx-en/search/?query=Databricks&page=1&order=date",
    "Security Boulevard": "https://securityboulevard.com/?s=Databricks",
    "Security Magazine": "https://www.securitymagazine.com/search?query=Databricks",
    "SecurityWeek": "https://www.securityweek.com/?s=Databricks",
    "SiliconANGLE": "https://siliconangle.com/?s=Databricks",
    "Spiceworks": "https://community.spiceworks.com/search?q=Databricks%20order%3Alatest",
    "TechCrunch": "https://techcrunch.com/?s=Databricks",
    "TechRadar Pro": "https://www.techradar.com/search?searchTerm=Databricks&articleType=all&sortBy=publishedDate",
    "TechRepublic": "https://www.techrepublic.com/search/?q=Databricks&o=2",
    "TechTarget": "https://www.techtarget.com/search",
    "The Hacker News": "https://cse.google.com/cse?q=Databricks&cx=partner-pub-7983783048239650%3A3179771210#gsc.tab=0&gsc.q=Databricks&gsc.sort=date",
    "The Record": "https://therecord.media/search-results?term=Databricks",
    "The Register": "https://www.theregister.com/search/?q=Databricks",
    "The Verge": "https://www.theverge.com/search?q=Databricks",
    "VentureBeat": "https://venturebeat.com/?s=Databricks",
    "ZDNet": "https://www.zdnet.com/search/?searchQuery=Databricks",
}

AI_SEARCH_LINKS = {
    "ABC News": "https://abcnews.go.com/search?searchtext=artificial+intelligence",
    "Associated Press": "https://apnews.com/search?q=artificial+intelligence#nt=navsearch",
    "Axios": "https://www.axios.com/results?q=artificial+intelligence&sort=1",
    "BBC": "https://www.bbc.com/search?q=artificial+intelligence",
    "Bloomberg": "https://www.bloomberg.com/search?query=artificial+intelligence",
    "Boston Business Journal": "https://www.bizjournals.com/boston/search?s=2&q=artificial+intelligence",
    "Boston Globe": "https://www.bostonglobe.com/search/?q=artificial+intelligence",
    "Business Insider": "https://www.businessinsider.com/answers#artificial+intelligence",
    "CBS News": "https://www.cbsnews.com/search/?q=artificial+intelligence",
    "CNBC": "https://www.cnbc.com/search/?query=artificial+intelligence&qsearchterm=artificial+intelligence",
    "CNN": "https://www.cnn.com/search?q=artificial+intelligence&from=0&size=10&page=1&sort=newest&types=all&section=",
    "Fast Company": "https://www.fastcompany.com/",
    "Financial Times": "https://www.ft.com/search?q=artificial+intelligence&sort=date&isFirstView=true",
    "Forbes": "https://www.forbes.com/search/?q=artificial+intelligence",
    "Fortune": "https://fortune.com/search/artificial+intelligence/",
    "Harvard Business Review": "https://hbr.org/search?term=artificial+intelligence",
    "Inc.": "https://www.inc.com/",
    "MIT Technology Review": "https://www.technologyreview.com/search/?s=artificial+intelligence",
    "Morning Brew": "https://www.morningbrew.com/search?tag=&q=artificial+intelligence",
    "NBC News": "https://www.nbcnews.com/search/?q=artificial+intelligence",
    "New York Times": "https://www.nytimes.com/search?dropmab=false&query=artificial+intelligence&sort=best",
    "Newsweek": "https://search.newsweek.com/",
    "NPR": "https://www.npr.org/search/?query=artificial+intelligence&page=1&range%5BlastModifiedDate%5D%5Bmin%5D=1752537600",
    "Politico": "https://www.politico.com/search?s=newest&userInitiated=true&q=artificial+intelligence",
    "Reuters": "https://www.reuters.com/site-search/?query=artificial+intelligence&date=past_week",
    "The Hill": "https://thehill.com/?s=artificial+intelligence&order=desc&orderby=relevance",
    "USA Today": "https://www.usatoday.com/search/?q=artificial+intelligence",
    "Wall Street Journal": "https://www.wsj.com/search?query=artificial+intelligence",
    "Washington Post": "https://www.washingtonpost.com/search/?query=artificial+intelligence+last+two+weeks",
    "WIRED": "https://www.wired.com/search/?q=artificial+intelligence&sort=publishdate+desc",
    "Yahoo! News": "https://news.search.yahoo.com/search?p=artificial+intelligence",
    "Ars Technica": "https://arstechnica.com/#gsc.tab=0&gsc.q=artificial+intelligence&gsc.sort=date",
    "Bleeping Computer": "https://www.bleepingcomputer.com/search/artificial+intelligence/",
    "CIO.com": "https://www.cio.com/search/?q=artificial+intelligence",
    "CIO Dive": "https://www.ciodive.com/search/?q=artificial+intelligence&selected_facets=&topics=&sortby=on",
    "CNET": "https://www.cnet.com/search/?searchQuery=artificial+intelligence",
    "ComputerWeekly": "https://www.computerweekly.com/search",
    "Computerworld": "https://www.computerworld.com/search/?q=artificial+intelligence",
    "CPO Magazine": "https://www.cpomagazine.com/?s=artificial+intelligence",
    "CRN": "https://www.crn.com/search?q=artificial+intelligence",
    "CSO Online": "https://www.csoonline.com/search/?q=artificial+intelligence",
    "Cyberscoop": "https://cyberscoop.com/?s=artificial+intelligence",
    "Cybersecurity Dive": "https://www.cybersecuritydive.com/search/?q=artificial+intelligence&selected_facets=section_exact%3Anews&topics=&sortby=on",
    "Dark Reading": "https://www.darkreading.com/search?q=artificial+intelligence&sort=newest",
    "Datamation": "https://www.datamation.com/?s=artificial+intelligence",
    "Decipher": "https://duo.com/search#?cludoquery=artificial+intelligence&cludopage=1&cludoinputtype=standard",
    "Dice Insights": "https://www.dice.com/career-advice/search?query=artificial+intelligence",
    "eSecurity Planet": "https://www.esecurityplanet.com/?s=artificial+intelligence",
    "eWEEK": "https://www.eweek.com/?s=artificial+intelligence",
    "InformationWeek": "https://www.informationweek.com/search?q=artificial+intelligence&sort=newest",
    "Infosecurity Magazine": "https://www.infosecurity-magazine.com/search/?keywords=artificial+intelligence",
    "InfoWorld": "https://www.infoworld.com/search/?q=artificial+intelligence",
    "ISMG": "https://www.ismg.io/search/artificial+intelligence",
    "IT Brew": "https://www.itbrew.com/search?q=artificial+intelligence&search=nav",
    "ITPro Today": "https://www.itprotoday.com/search?q=artificial+intelligence&sort=newest",
    "Krebs on Security": "https://krebsonsecurity.com/?s=artificial+intelligence",
    "Runtime.News": "https://www.runtime.news/tag/artificial-intelligence/",
    "SC Media": "https://www.scworld.com/search?q=artificial+intelligence",
    "SD Times": "https://sdtimes.com/?s=artificial+intelligence",
    "SDxCentral": "https://www.sdxcentral.com/sdx-en/search/?query=artificial+intelligence&page=1&order=date",
    "Security Boulevard": "https://securityboulevard.com/?s=artificial+intelligence",
    "Security Magazine": "https://www.securitymagazine.com/search?query=artificial+intelligence",
    "SecurityWeek": "https://www.securityweek.com/?s=artificial+intelligence",
    "SiliconANGLE": "https://siliconangle.com/?s=artificial+intelligence",
    "Spiceworks": "https://community.spiceworks.com/search?q=artificial+intelligence%20order%3Alatest",
    "TechCrunch": "https://techcrunch.com/?s=artificial+intelligence",
    "TechRadar Pro": "https://www.techradar.com/search?searchTerm=artificial+intelligence&articleType=all&sortBy=publishedDate",
    "TechRepublic": "https://www.techrepublic.com/search/?q=artificial+intelligence&o=2",
    "TechTarget": "https://www.techtarget.com/search",
    "The Hacker News": "https://cse.google.com/cse?q=artificial+intelligence&cx=partner-pub-7983783048239650%3A3179771210#gsc.tab=0&gsc.q=artificial+intelligence&gsc.sort=date",
    "The Record": "https://therecord.media/search-results?term=artificial+intelligence",
    "The Register": "https://www.theregister.com/search/?q=artificial+intelligence",
    "The Verge": "https://www.theverge.com/search?q=artificial+intelligence",
    "VentureBeat": "https://venturebeat.com/?s=artificial+intelligence",
    "ZDNet": "https://www.zdnet.com/search/?searchQuery=artificial+intelligence",
}

CYBER_SECURITY_SEARCH_LINKS = {
    "ABC News": "https://abcnews.go.com/search?searchtext=cybersecurity",
    "Associated Press": "https://apnews.com/search?q=cybersecurity#nt=navsearch",
    "Axios": "https://www.axios.com/results?q=cybersecurity&sort=1",
    "BBC": "https://www.bbc.com/search?q=cybersecurity",
    "Bloomberg": "https://www.bloomberg.com/search?query=cybersecurity",
    "Boston Business Journal": "https://www.bizjournals.com/boston/search?s=2&q=cybersecurity",
    "Boston Globe": "https://www.bostonglobe.com/search/?q=cybersecurity",
    "Business Insider": "https://www.businessinsider.com/answers#cybersecurity",
    "CBS News": "https://www.cbsnews.com/search/?q=cybersecurity",
    "CNBC": "https://www.cnbc.com/search/?query=cybersecurity&qsearchterm=cybersecurity",
    "CNN": "https://www.cnn.com/search?q=cybersecurity&from=0&size=10&page=1&sort=newest&types=all&section=",
    "Fast Company": "https://www.fastcompany.com/",
    "Financial Times": "https://www.ft.com/search?q=cybersecurity&sort=date&isFirstView=true",
    "Forbes": "https://www.forbes.com/search/?q=cybersecurity",
    "Fortune": "https://fortune.com/search/cybersecurity/",
    "Harvard Business Review": "https://hbr.org/search?term=cybersecurity",
    "Inc.": "https://www.inc.com/",
    "MIT Technology Review": "https://www.technologyreview.com/search/?s=cybersecurity",
    "Morning Brew": "https://www.morningbrew.com/search?tag=&q=cybersecurity",
    "NBC News": "https://www.nbcnews.com/search/?q=cybersecurity",
    "New York Times": "https://www.nytimes.com/search?dropmab=false&query=cybersecurity&sort=best",
    "Newsweek": "https://search.newsweek.com/",
    "NPR": "https://www.npr.org/search/?query=cybersecurity&page=1&range%5BlastModifiedDate%5D%5Bmin%5D=1752537600",
    "Politico": "https://www.politico.com/search?s=newest&userInitiated=true&q=cybersecurity",
    "Reuters": "https://www.reuters.com/site-search/?query=cybersecurity&date=past_week",
    "The Hill": "https://thehill.com/?s=cybersecurity&order=desc&orderby=relevance",
    "USA Today": "https://www.usatoday.com/search/?q=cybersecurity",
    "Wall Street Journal": "https://www.wsj.com/search?query=cybersecurity",
    "Washington Post": "https://www.washingtonpost.com/search/?query=cybersecurity+last+two+weeks",
    "WIRED": "https://www.wired.com/search/?q=cybersecurity&sort=publishdate+desc",
    "Yahoo! News": "https://news.search.yahoo.com/search?p=cybersecurity",
    "Ars Technica": "https://arstechnica.com/#gsc.tab=0&gsc.q=cybersecurity&gsc.sort=date",
    "Bleeping Computer": "https://www.bleepingcomputer.com/search/cybersecurity/",
    "CIO.com": "https://www.cio.com/search/?q=cybersecurity",
    "CIO Dive": "https://www.ciodive.com/search/?q=cybersecurity&selected_facets=&topics=&sortby=on",
    "CNET": "https://www.cnet.com/search/?searchQuery=cybersecurity",
    "ComputerWeekly": "https://www.computerweekly.com/search",
    "Computerworld": "https://www.computerworld.com/search/?q=cybersecurity",
    "CPO Magazine": "https://www.cpomagazine.com/?s=cybersecurity",
    "CRN": "https://www.crn.com/search?q=cybersecurity",
    "CSO Online": "https://www.csoonline.com/search/?q=cybersecurity",
    "Cyberscoop": "https://cyberscoop.com/?s=cybersecurity",
    "Cybersecurity Dive": "https://www.cybersecuritydive.com/search/?q=cybersecurity&selected_facets=section_exact%3Anews&topics=&sortby=on",
    "Dark Reading": "https://www.darkreading.com/search?q=cybersecurity&sort=newest",
    "Datamation": "https://www.datamation.com/?s=cybersecurity",
    "Decipher": "https://duo.com/search#?cludoquery=cybersecurity&cludopage=1&cludoinputtype=standard",
    "Dice Insights": "https://www.dice.com/career-advice/search?query=cybersecurity",
    "eSecurity Planet": "https://www.esecurityplanet.com/?s=cybersecurity",
    "eWEEK": "https://www.eweek.com/?s=cybersecurity",
    "InformationWeek": "https://www.informationweek.com/search?q=cybersecurity&sort=newest",
    "Infosecurity Magazine": "https://www.infosecurity-magazine.com/search/?keywords=cybersecurity",
    "InfoWorld": "https://www.infoworld.com/search/?q=cybersecurity",
    "ISMG": "https://www.ismg.io/search/cybersecurity",
    "IT Brew": "https://www.itbrew.com/search?q=cybersecurity&search=nav",
    "ITPro Today": "https://www.itprotoday.com/search?q=cybersecurity&sort=newest",
    "Krebs on Security": "https://krebsonsecurity.com/?s=cybersecurity",
    "Runtime.News": "https://www.runtime.news/tag/cybersecurity/",
    "SC Media": "https://www.scworld.com/search?q=cybersecurity",
    "SD Times": "https://sdtimes.com/?s=cybersecurity",
    "SDxCentral": "https://www.sdxcentral.com/sdx-en/search/?query=cybersecurity&page=1&order=date",
    "Security Boulevard": "https://securityboulevard.com/?s=cybersecurity",
    "Security Magazine": "https://www.securitymagazine.com/search?query=cybersecurity",
    "SecurityWeek": "https://www.securityweek.com/?s=cybersecurity",
    "SiliconANGLE": "https://siliconangle.com/?s=cybersecurity",
    "Spiceworks": "https://community.spiceworks.com/search?q=cybersecurity%20order%3Alatest",
    "TechCrunch": "https://techcrunch.com/?s=cybersecurity",
    "TechRadar Pro": "https://www.techradar.com/search?searchTerm=cybersecurity&articleType=all&sortBy=publishedDate",
    "TechRepublic": "https://www.techrepublic.com/search/?q=cybersecurity&o=2",
    "TechTarget": "https://www.techtarget.com/search",
    "The Hacker News": "https://cse.google.com/cse?q=cybersecurity&cx=partner-pub-7983783048239650%3A3179771210#gsc.tab=0&gsc.q=cybersecurity&gsc.sort=date",
    "The Record": "https://therecord.media/search-results?term=cybersecurity",
    "The Register": "https://www.theregister.com/search/?q=cybersecurity",
    "The Verge": "https://www.theverge.com/search?q=cybersecurity",
    "VentureBeat": "https://venturebeat.com/?s=cybersecurity",
    "ZDNet": "https://www.zdnet.com/search/?searchQuery=cybersecurity",
}


